baseURL = "https://rogena.me"
languageCode = "en-us"
title = "do{coffee; code;} while(true)"
theme = "cactus"
copyright = "Jason Rogena"

[[params.social]]
  name = "github"
  link = "https://github.com/jasonrogena"

[[params.social]]
  name = "email"
  link = "null+blog@rogena.me"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/jrogena"

[params]
  description = "I am a Site Reliability Engineer currently based in Nairobi. If I'm not on my desk, I'll probably be in the kitchen or gym. I'm also a father of seven (plants). Herein lies, mostly tech-related, exploits in the form of blog posts and projects. Feel free to reach out on email or Twitter if you'd like to chat."
  colortheme = "white"
  mainSectionTitle = "Posts"
  showProjectsList = true
  projectsUrl = "https://github.com/jasonrogena"
  rss = true
  postsOnHomePage = 5
  tagsOverview = true
  showReadTime = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
